name: northwest
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  gradient_text: ^1.0.2
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  image_path_android: "lib/assets/icons/icon.png"
  image_path_ios: "lib/assets/icons/icon.png"
  android: true 
  ios: true 

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true

  assets:
   - lib/assets/icons/icon.png

  fonts:
    - family: Prompt
      fonts:
        - asset: lib/assets/fonts/Prompt-Regular.ttf
    - family: PromptBold
      fonts:
        - asset: lib/assets/fonts/Prompt-Bold.ttf
  